# Generated by Django 3.2.3 on 2026-05-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_collection_collectionitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_collection'),
        ),
    ]
